global:
  scrape_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs: [{ targets: ["prometheus:9090"] }]
  - job_name: otel-collector
    static_configs: [{ targets: ["otel-collector:8880"] }]
  - job_name: backend
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:8080"]
storage:
  tsdb:
    out_of_order_time_window: 30m